"""Regenerate + clean pybind11 type stubs for the ``quant_engine`` extension.

pybind11-stubgen produces a working stub but its default output fails
``ruff check``:

- enum class locations are unqualified → E501 when the inline ``# value = …``
  comment expands the ``__members__`` line beyond 100 columns even after
  ``ruff format`` wraps it;
- imports are unsorted;
- docstring comments contain repr-style values that ruff can't auto-split.

This script runs stubgen with the enum-location hint, replaces the
unwrappable ``__members__`` line with a short-form + ``# noqa: E501``
override, and applies ``ruff check --fix`` + ``ruff format`` so the
checked-in artefact passes ``make lint`` deterministically.

Re-run any time ``cpp/bindings/python_module.cpp`` gains or changes an
exported symbol; ``make stubs`` is the intended entry point.

Stdlib-only (except for the subprocess-invoked pybind11-stubgen and ruff,
which are dev-only deps).
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STUB_PARENT = REPO_ROOT / "src"
PACKAGE_DIR = STUB_PARENT / "quant_engine"
MODULE_STUB = PACKAGE_DIR / "quant_engine.pyi"

# stubgen emits `__members__` as one long line with an autogenerated value
# comment; replace with short-form + noqa so ruff format doesn't blow past
# the column limit on the next pass.
_MEMBERS_PATTERN = re.compile(r"__members__: typing\.ClassVar\[dict\[str, SlippageModel\]\][^\n]*")
_MEMBERS_REPLACEMENT = "__members__: typing.ClassVar[dict[str, SlippageModel]]  # noqa: E501"

# Rewrite stubgen's `numpy.ndarray[numpy.X]` to `numpy.typing.NDArray[X]` —
# numpy 2.x's `Generic[Shape, DType]` resolves the former as
# `ndarray[Shape=X, DType=Any]` (wrong slot). Also injects the missing
# `numpy.typing` import.
_NDARRAY_PATTERN = re.compile(r"numpy\.ndarray\[numpy\.(\w+)\]")
_NDARRAY_REPLACEMENT = r"numpy.typing.NDArray[numpy.\1]"


def _run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True, cwd=REPO_ROOT)


def main() -> int:
    _run(
        [
            "pybind11-stubgen",
            "quant_engine",
            "-o",
            str(STUB_PARENT),
            "--enum-class-locations",
            "SlippageModel:quant_engine",
        ]
    )

    text = MODULE_STUB.read_text()
    new_text, n_replaced = _MEMBERS_PATTERN.subn(_MEMBERS_REPLACEMENT, text)
    if n_replaced != 1:
        print(
            f"ERROR: expected exactly one __members__ match in {MODULE_STUB}, "
            f"found {n_replaced}. Has stubgen output format changed?",
            file=sys.stderr,
        )
        return 1
    new_text, n_ndarray = _NDARRAY_PATTERN.subn(_NDARRAY_REPLACEMENT, new_text)
    if n_ndarray > 0 and "import numpy.typing" not in new_text:
        new_text = new_text.replace("import numpy\n", "import numpy\nimport numpy.typing\n", 1)
    MODULE_STUB.write_text(new_text)

    # --fix-only (not --fix) so unfixable violations don't poison the exit
    # code before the second format pass gets a chance to clear them.
    _run(["ruff", "format", str(PACKAGE_DIR)])
    _run(["ruff", "check", "--fix-only", str(PACKAGE_DIR)])
    _run(["ruff", "format", str(PACKAGE_DIR)])
    _run(["ruff", "check", str(PACKAGE_DIR)])
    print(f"stubs regenerated + cleaned: {MODULE_STUB.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
